- README.md
- examples/cos_bucket/README.md
- examples/cos_instance/README.md
- modules/cos_bucket/README.md
- modules/cos_bucket/output.tf
- modules/cos_instance/README.md
Corrected table format and changed provider from Google to IBM
> Corrected table format and changed provider from Google to IBM

- test/cos_instance_test.go
Configured default resource group
> Configured default resource group

- examples/bucket/output.tf
- modules/bucket/output.tf
remove duplicate output.tf file from cos bucket.
> remove duplicate output file

- README.md
> docs: fix status badge

- .releaserc
> ci: fix releaserc

- .gitmodules
- .secrets.baseline
- main.tf
- module-metadata.json
> fix: failing tflint rules

- .github/settings.yml
Adds name and description. Syncs with work in internal repo.
> ci: (settings) update name and description

- README.md
> docs: add note on provider configuration

- README.md
- examples/complete-multiple-buckets/README.md
- examples/complete-multiple-buckets/main.tf
- examples/complete-multiple-buckets/outputs.tf
- examples/complete-multiple-buckets/providers.tf
- examples/complete-multiple-buckets/variables.tf
- examples/complete-multiple-buckets/version.tf
- examples/complete/README.md
- examples/complete/main.tf
- examples/complete/outputs.tf
- examples/complete/providers.tf
- examples/complete/variables.tf
- examples/complete/version.tf
- tests/other_test.go
- tests/pr_test.go
Readme updated with better module description and examples including monitoring added. The complete example is now what is tested. 
> test: add monitoring examples

- tests/other_test.go
> test: fix other_test

- README.md
> fix: update readme and trigger release

- .github/workflows/notify.yml
> ci: add notify workflow

- .github/workflows/verify.yaml
- module.yaml
> ci: add verify workflow

- .github/workflows/verify.yaml
> fix verify syntax

- .github/workflows/verify.yml
> Update and rename verify.yaml to verify.yml

- module.yaml
Signed-off-by: Daniel Butler <dannyeb@gmail.com>
For iascable to auto-wire the output from the resource group to the input of this module we need to explicitly define it here. 
> fix: add dependency to the module.yaml

- .github/workflows/ci.yml
- cra-tf-validate-ignore-goals.json
Signed-off-by: Daniel Butler <dannyeb@gmail.com>
Adding CRA scan to the pipeline 
---
> ci: add cra scan to pipeline

- tests/pr_test.go
Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies.
---
> test: use value specified for at instance in submodule yaml

- .gitmodules
- .secrets.baseline
- main.tf
- module-metadata.json
- tests/pr_test.go
See https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/173
---
> fix: fix issue in s2s policy ids

- README.md
- module-metadata.json
- outputs.tf
Expose cos_instance_guid as output https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/191
---
> fix: exposed cos_instance_guid as output

- README.md
- cra-tf-validate-ignore-goals.json
- examples/complete/README.md
- examples/complete/main.tf
- main.tf
- module-metadata.json
- outputs.tf
- tests/go.mod
- tests/go.sum
- tests/pr_test.go
- variables.tf
Signed-off-by: Daniel Butler <dannyeb@gmail.com>
Adding support for CBRs
---
> feat: add cbr support

- tests/pr_test.go
> test: cleanup pr_test.go

- examples/complete/main.tf
- main.tf
- module-metadata.json
Update tags usage in example
---
> fix: CBR tags update

- README.md
remove known issue from doc - no longer relevant
---
> docs: remove known issue from doc - no longer relevant

- README.md
- main.tf
- module-metadata.json
- outputs.tf
Add direct endpoint to output for VPC
---
> feat: add direct endpoint output

- profiles/fscloud/main.tf
Intermittent failure in fscloud profile when sometimes the bucket creation happens before the policy is created. 
---
> fix: depend on policy

- README.md
Updating module status to graduated
---
> docs: Update module status

- README.md
- examples/basic/README.md
- examples/basic/main.tf
- examples/basic/outputs.tf
- examples/basic/providers.tf
- examples/basic/variables.tf
- examples/basic/version.tf
- profiles/fscloud/main.tf
- tests/other_test.go
- tests/pr_test.go
Basic example to create COS instance and bucket
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines …
> feat: added basic example

- .github/workflows/ci.yml
- .github/workflows/release.yml
bump to latest pipeline version
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a …
> ci: bump to latest pipeline version

- README.md
Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
If the CI pipeline doesn't run when you …
> fix: remove build badge

- README.md
- examples/complete/main.tf
- examples/existing-resources/main.tf
- main.tf
- module-metadata.json
- profiles/fscloud/README.md
- profiles/fscloud/main.tf
- profiles/fscloud/variables.tf
ibm_iam_authorization_policy can only be created when a encrypted buckets are created, not when a instance with no buckets is created or when only unencrypted buckets are created.
This change creates (or skips) the authorization policy when an encrypted bucket is requested.
fixes https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/352
Any consumer using multiple modules to create encrypted buckets will need to add `skip_iam_authorization_policy = true` to all but the first encrypted bucket created. Since the policy will be associated with the first bucket, all subsequent buckets, will …
> Authorization policy based on encrypted bucket

- docs/cos_icon.svg
add icon
```
/run pipeline
```
> docs: add icon

- examples/basic/catalogValidationValues.json.template
- examples/complete/catalogValidationValues.json.template
- examples/fscloud/catalogValidationValues.json.template
- examples/one-rate-plan/catalogValidationValues.json.template
- examples/replication/catalogValidationValues.json.template
added catalogValidationValues.json.template to all examples being imported to catalog. I won't generate a release with this PR, but I will with https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/444 and use that version to import to catalog
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit message …
> added catalogValidationValues.json.template to all examples being imported to catalog

- ibm_catalog.json
caption and description cannot be empty, so for now leaving as a 1 spaced string
```
/run pipeline
```
> caption and description cannot be empty in ibm_catalog.josn

- ibm_catalog.json
Makes the list of features parallel (start with verb).
Merges into PR #459 
```
/run pipeline
```
> Update features ibm_catalog.json

- .secrets.baseline
- README.md
add catalog badge
```
/run pipeline
```
> docs: add catalog badge

- README.md
> Fix the catalog badge link

- .secrets.baseline
- examples/fscloud/README.md
- examples/fscloud/main.tf
- examples/fscloud/variables.tf
- tests/pr_test.go
Update fscloud example to extend CBR to include public permissions from schematics
Issue: 6450
```
/run pipeline
```
> fix: cbr for schematics in fscloud

- modules/fscloud/README.md
Correct usage example for fscloud module
https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/542
```
/run pipeline
```
> fix: usage example fscloud readme

- modules/fscloud/README.md
- modules/fscloud/main.tf
- modules/fscloud/outputs.tf
Adds support for existing cos instance ID.
https://github.ibm.com/GoldenEye/issues/issues/8071
```
/run pipeline
```
> fix: add support for exiting cos id

- tests/scripts/pre-validation-deploy-cos-regional.sh
Issue : https://github.ibm.com/GoldenEye/issues/issues/8200#event-314908193
```
/run pipeline
```
> fix: assigning values to variables twice in catalog validation

- tests/scripts/pre-validation-deploy-cos-cross-region.sh
- tests/scripts/pre-validation-deploy-cos-regional.sh
> fix: seperate tfvars for each validation

- .catalog-onboard-pipeline.yaml
- tests/scripts/post-validation-deploy-cos-cross-region.sh
- tests/scripts/post-validation-deploy-cos-regional.sh
> fix: seperate post validation for each bucket

- .github/settings.yml
> Add `deployable-architecture` topic

- cra-config.yaml
- ibm_catalog.json
> Update DAs to use fscloud 1.6.0 profile

- solutions/secure-cross-regional-bucket/catalogValidationValues.json.template
- solutions/secure-regional-bucket/catalogValidationValues.json.template
> ci: remove unused keys from catalog json template

- main.tf
condition has nothing to do with archive_days
Update conditional statement regarding setting `cross_region_location` and `archive_days`.
```
/run pipeline
```
> fix: condition has nothing to do with archive_days

- variables.tf
per https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/626#issuecomment-2147136914
The value of the role should be "NONE" similar like cli (case-sensitive)
```
/run pipeline
```
> fix: none is case sensitive

- solutions/secure-cross-regional-bucket/catalogValidationValues.json.template
- solutions/secure-cross-regional-bucket/main.tf
- solutions/secure-cross-regional-bucket/provider.tf
- solutions/secure-cross-regional-bucket/variables.tf
- solutions/secure-regional-bucket/catalogValidationValues.json.template
- solutions/secure-regional-bucket/main.tf
- solutions/secure-regional-bucket/provider.tf
- solutions/secure-regional-bucket/variables.tf
- tests/pr_test.go
Resolves: https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/635
```
/run pipeline
```
> fix: programmatically determines the kms region and guid from the crn

- solutions/instance/main.tf
- solutions/instance/variables.tf
add support to use an optional prefix in the COS instances DA
```
/run pipeline
```
> feat: add support to use an optional prefix in the COS instances DA

- ibm_catalog.json
It was pointing to a internal catalog, so was not rendering in community catalog:
```
/run pipeline
```
> fix: update bucket DAs dependencies

- ibm_catalog.json
"ibm_created" tag is required so tile shows that is IBM and not Community maintained
```
/run pipeline
```
> Update ibm_catalog.json to add "ibm_created" tag

- solutions/secure-cross-regional-bucket/outputs.tf
- solutions/secure-regional-bucket/outputs.tf
Adding the additional outputs to be able to pass these down through a stack which is currently not able to read individual elements in a json/list as per the current output
```
/run pipeline
```
> feat: add individual cos bucket detail outputs

- solutions/instance/DA-resource-keys.md
- solutions/instance/variables.tf
#664 add some documentation for the DA for resource_keys variable which has a complex type
Improve variable documentation.
```
/run pipeline
```
> doc: resource key documentation for DA

- examples/advanced/main.tf
- solutions/secure-cross-regional-bucket/main.tf
- solutions/secure-regional-bucket/main.tf
renovate identified that a variable change is required along with the KMS bump.
This impacts the DA, so a release is required.
Dependancy upgrade to kms-all-inclusive
```
/run pipeline
```
> fix(deps): bump kms

- solutions/instance/main.tf
- solutions/instance/outputs.tf
https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/695
```
/run pipeline
```
> fix: condition to not create sm credentials

- main.tf
added a validation that does not allow create_cos_instance to be true,
if a value is being passed for existing_cos_instance_id.
issue:https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/697
added a validation that does not allow create_cos_instance to be true,
if a value is being passed for existing_cos_instance_id
```
/run pipeline
```
- Include information that …
> fix: added validation for create_cos_instance and existing_cos_instance_id variable.

- README.md
- modules/fscloud/README.md
- modules/fscloud/outputs.tf
- outputs.tf
add 'cos_account_id' output
```
/run pipeline
```
> feat: add 'cos_account_id' output

- solutions/secure-cross-regional-bucket/main.tf
- solutions/secure-regional-bucket/main.tf
https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/742
https://github.ibm.com/GoldenEye/issues/issues/11138
Parse `existing_cos_instance_id` which is required variable for both DA to get account id
```
/run pipeline
```
- …
> fix: remove ibm_iam_account_settings from da

- solutions/secure-cross-regional-bucket/main.tf
- solutions/secure-regional-bucket/main.tf
The DA use of kms-all-inclusive was broken by upgrading the module version without associated (required) code changes.
This pull request adds the required code changes.
```
/run pipeline
```
> fix(deps): code change should have been done with KMS bump

- cra-config.yaml
https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/746
```
/run pipeline
```
> Update cra-config.yaml to scan DAs

- README.md
- examples/advanced/main.tf
- examples/advanced/version.tf
- examples/basic/version.tf
- examples/fscloud/main.tf
- examples/fscloud/version.tf
- examples/one-rate-plan/version.tf
- examples/replication/version.tf
- main.tf
- modules/buckets/README.md
- modules/buckets/version.tf
- modules/fscloud/README.md
- modules/fscloud/main.tf
- modules/fscloud/version.tf
- version.tf
Update terraform terraform-ibm-modules/cbr/ibm to v1.28.1
Update required provider version to >= 1.70.0 to pick up the fix for this provider issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5590
Update terraform terraform-ibm-modules/cbr/ibm to v1.28.1
Update required provider version to >= 1.70.0 to pick up the fix for this provider issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5590
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the …
> fix(deps): update terraform terraform-ibm-modules/cbr/ibm to v1.28.1

- modules/buckets/main.tf
- solutions/secure-cross-regional-bucket/main.tf
- solutions/secure-regional-bucket/main.tf
Same changes that were done in https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/764 are also done now in the submodules and DAs as they were missed in initial PR
```
/run pipeline
```
> Updated the KMS auth policy so its scoped to the exact KMS Key (part2)

- solutions/instance/outputs.tf
The cos_instance_name variable  generated by the DA from \<prefix>\-\<name>added to output.tf file in  DA
[Git Issue](https://github.ibm.com/GoldenEye/issues/issues/11177)
Add a output to expose cos_instance_ name in DA
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release …
> feat : added cos_instance_name in DA output

- solutions/instance/outputs.tf
Add in the outputs for the resource group name to be used by other DAs in a stack/addon
```
/run pipeline
```
> feat: added new outputs to the COS DA

- ibm_catalog.json
- solutions/instance/DA-cbr_rules.md
- solutions/instance/main.tf
- solutions/instance/variables.tf
- solutions/secure-cross-regional-bucket/DA-cbr_rules.md
- solutions/secure-cross-regional-bucket/main.tf
- solutions/secure-cross-regional-bucket/variables.tf
- solutions/secure-regional-bucket/DA-cbr_rules.md
- solutions/secure-regional-bucket/main.tf
- solutions/secure-regional-bucket/variables.tf
Exposed CBRs in DA
[GIT Issue](https://github.ibm.com/GoldenEye/issues/issues/11829)
Exposes CBRs in DA
```
/run pipeline
```
> feat:exposing CBRs in DA

- .secrets.baseline
- solutions/instance/DA-types.md
- solutions/instance/main.tf
- solutions/instance/variables.tf
- tests/pr_test.go
Issue: #817
The logic for creating the service credential only worked for roles where the CRN service-name was 'iam'. Syncing this module with the secret manager module, to expose https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/issues/268 and the secret module, to expose https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-secret/issues/249.
Additional changes are included in pr_test.go to include a cloud-object-service serviceRole based service credential.
The DA does support secret creation and the internal structure of a complex variable has changed. Any consumer using this feature to create service credentials will have to replace the existing 'service_credentials_source_service_role' with the equivalent …
> fix: service credential source service role

- README.md
- examples/advanced/version.tf
- examples/basic/version.tf
- examples/fscloud/version.tf
- examples/one-rate-plan/version.tf
- examples/replication/version.tf
- main.tf
- modules/buckets/README.md
- modules/buckets/version.tf
- modules/fscloud/README.md
- modules/fscloud/version.tf
- solutions/secure-cross-regional-bucket/main.tf
- solutions/secure-cross-regional-bucket/variables.tf
- solutions/secure-regional-bucket/main.tf
- solutions/secure-regional-bucket/variables.tf
- variables.tf
- version.tf
updated code to use cross-object referencing for validations
```
/run pipeline
```
> feat: updated code to use cross-object referencing for validations

- solutions/instance/variables.tf
Updated prefix value as `dev` in DA .
```
/run pipeline
```
> Update prefix value in DA

- ibm_catalog.json
- solutions/instance/variables.tf
Sync IBM catalog JSON with all three DAs
No release required, since existing catalog tiles are unaffected by this change
```
/run pipeline
```
> Ibm catalog

- README.md
- examples/advanced/version.tf
- examples/basic/version.tf
- examples/fscloud/version.tf
- examples/one-rate-plan/version.tf
- examples/replication/version.tf
- modules/buckets/README.md
- modules/buckets/version.tf
- modules/fscloud/README.md
- modules/fscloud/version.tf
- solutions/instance/version.tf
- solutions/secure-cross-regional-bucket/version.tf
- solutions/secure-regional-bucket/version.tf
- version.tf
> chore: bump provider version

- tests/scripts/pre-validation-deploy-cos-cross-region.sh
- tests/scripts/pre-validation-deploy-cos-regional.sh
`existing_cos_instance_id` was renamed to `existing_cos_instance_crn` in https://github.com/terraform-ibm-modules/terraform-ibm-cos/releases/tag/v8.20.0 so it broke this script. The PR updates the script which will fix https://github.ibm.com/GoldenEye/issues/issues/12912
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The …
> fix pre-validation scripts

- solutions/instance/outputs.tf
- tests/scripts/pre-validation-deploy-cos-cross-region.sh
- tests/scripts/pre-validation-deploy-cos-regional.sh
feat: expose cos instance crn as output in COS instance DA
[Issue](https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/839)
```
/run pipeline
```
> feat: expose cos instance crn as output in COS instance DA

- solutions/instance/version.tf
- solutions/secure-cross-regional-bucket/version.tf
- solutions/secure-regional-bucket/version.tf
`1.78.2` is required to pick up the fix for https://github.com/IBM-Cloud/terraform-provider-ibm/pull/6235
```
/run pipeline
```
> fix(deps): update DA provder version to 1.78.2

- solutions/secure-cross-regional-bucket/catalogValidationValues.json.template
- solutions/secure-regional-bucket/catalogValidationValues.json.template
> fix: pass prefix value for bucket DA catalog validation

- ibm_catalog.json
> add support for ca-mon in regional bucket DA

- solutions/cross-regional-bucket/security-enforced/catalogValidationValues.json.template
Pass `existing_cos_instance_crn` as catalog validation value.
```
/run pipeline
```
> add existing_cos_instance_crn in catalogValidation

- .secrets.baseline
- README.md
- main.tf
https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/900
[remove workaround for lifecycle wait for create
](https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/900)
```
/run pipeline
```
- Use the **Squash and …
> fix: remove workaround for lifecyle wait for create

- solutions/cross-regional-bucket/fully-configurable/main.tf
- solutions/regional-bucket/fully-configurable/main.tf
https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/933
This PR includes the fix for the count logic in the kms block in cos bucket DAs.
```
/run pipeline
```
> fix: kms block logic bug

- ibm_catalog.json
- solutions/instance/variables.tf
issue: https://github.ibm.com/GoldenEye/issues/issues/15774
```
/run pipeline
```
> Update dependency desc
