README.md, examples/bucket-without-tracking-monitoring/main.tf, examples/bucket-without-tracking-monitoring/variables.tf, main.tf, module-metadata.json, variables.tf
Add tags support for the cloud object storage and key protect instances.
Add example code on how to set the cloud object storage tags.
Remove 90 day retention from example. Exposing a first example that potentially retains the objects for 90 days seems counter intuitive. Experiment first and enable it later?
I am happy to take comments on the variable names, maybe keep `tags`, rather than `cos_tags` to aid migration from version 1 to version 3?
Retention may be an unwanted change. Disabling retention in the example, since any objects created could not be deleted for 90 days.
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message …
=> feat: tags support

README.md, main.tf, module-metadata.json, variables.tf
https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/70
The creation of buckets should be optional. This will now be possible but creation is on by default.
=> fix: make bucket creation optional

main.tf
Fix an issue where the auth policy is created even when the module is configured to not create the key protect instance.
Spotted as part of updating internal module references. The original internal version of the module had the line that is committed in this PR.
=> fix: create authorization policy only if creating key protect instance

README.md, examples/complete/main.tf, examples/complete/outputs.tf, examples/complete/providers.tf, examples/complete/version.tf, examples/existing-resources/README.md, examples/existing-resources/main.tf, examples/existing-resources/version.tf, main.tf, module-metadata.json, outputs.tf, variables.tf, version.tf
- remove direct support for creating key protect instance / key rings / keys from this module (use https://github.com/terraform-ibm-modules/terraform-ibm-key-protect-all-inclusive directly going forward). This will be a major version change due to the may variables that have been removed, and change of outputs
docs:
- update usage to match changes
=> feat: remove support for creating key protect resources

module.yaml
update module.yaml - restapi is no longer required
=> ci: update module.yaml - restapi is no longer required

README.md, module-metadata.json, variables.tf
In https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/130 the default value of var.activity_tracker_crn was incorrectly removed.
---
=> fix: add back default value of null for actitivy tracker crn input var

README.md, main.tf, module-metadata.json, outputs.tf, variables.tf
Add bucket_storage_class variable to allow users to select their storage class type, add validation for the variable to ensure proper value is passed, default set to "standard" to stay in line with previous versions of the module.
Git Issue: https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/209
Add variable `var.bucket_storage_class` to allow selection of available storage classes for buckets created by the module.
---
=> feat: add bucket_storage_class variable

.github/workflows/ci.yml, LICENCE, README.md, examples/fscloud/README.md, examples/fscloud/main.tf, examples/fscloud/outputs.tf, examples/fscloud/providers.tf, examples/fscloud/variables.tf, examples/fscloud/version.tf, main.tf, module-metadata.json, profiles/fscloud/README.md, profiles/fscloud/main.tf, profiles/fscloud/outputs.tf, profiles/fscloud/variables.tf, profiles/fscloud/version.tf, tests/pr_test.go, variables.tf
Adding FS cloud profile and tests
---
=> fscloud profile and example

README.md, examples/basic/version.tf, examples/complete/version.tf, examples/existing-resources/version.tf, examples/fscloud/version.tf, examples/one-rate-plan/version.tf, examples/replication/version.tf, module-metadata.json, profiles/fscloud/README.md, profiles/fscloud/version.tf, version.tf
Bump provider version to pick up bug fix for auth policies in 1.54.0
Update IBM provider to v1.54.0
```
/run pipeline
```
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of …
=> fix: upgrade provider to 1.54.0

modules/fscloud/main.tf
`kms_guid` is optional, and only required when creating the auth policy. Updating validation to reflect this.
```
/run pipeline
```
=> fix: fix bug in kms_guid validation

main.tf
Issue: 7308
Upgrades from earlier to version to this version may show a time_sleep.wait_for_authorization_policy being deleted if they are skipping authorisation policy creation. This is expected, since there is no need to delay if the authorisation policy already exists.
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The …
=> fix: delay before using policy

.catalog-onboard-pipeline.yaml
auto mark modules as ready in catalog now that pipeline supports not publishing during code freeze windows
```
/run pipeline
```
=> ci: auto mark modules as ready in catalog

outputs.tf
https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/558
```
/run pipeline
```
=> fix: Don't output bucket name until it exists

variables.tf
Relax validation on retention duration variables. When retention is not enabled, the values for each of the duration
variables could be null.
```
/run pipeline
```
=> fix: validation to allow null values

modules/buckets/main.tf
The bucket creation to occurring before the auth policy is created due to missing depends_on
```
/run pipeline
```
=> fix: fix bug related to missing KMS auth policy

ibm_catalog.json
In https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/654 we removed the catalog ID, as it was pointing to a private catalog. However since the dependency DA is actually in community (and not main catalog), we need to add the catalog ID of the community registry
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. …
=> fix: add community catalog id in dependencies section of ibm_catalog.json

.catalog-onboard-pipeline.yaml
disable COS module onboarding to catalog - we reached the limit in the module registry - catalog team are doing backend refactoring to handle this
```
/run pipeline
```
=> ci: disable COS module onboarding

solutions/instance/catalogValidationValues.json.template, solutions/instance/main.tf
PR: https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/708
- Added validation for `var.existing_secrets_manager_instance_crn` when `var.skip_cos_sm_auth_policy` is false
- Added "skip_cos_sm_auth_policy": true in `solutions/instance/catalogValidationValues.json.template` as we are not creating sm credentials while catalog validation
```
/run pipeline
```
- Include …
=> fix: added secrets manager crn validation when var.skip_cos_sm_auth_policy is false

variables.tf
Retention rate for the buckets has been adjusted to allow default, min or max to be 0.
Requested in: https://github.ibm.com/dreadnought/dreadnought-user-request/issues/973
```
/run pipeline
```
=> fix: allow bucket retention to be zero

ibm_catalog.json
Updates both cos bucket extension DAs to mark the dependant DA as optional. The user can deploy the extension DA using a COS instance that may not of been provisioned with the dependant DA.
This is needed because catalog pushed a changed where by default, optional is now true.
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. …
=> fix: update both cos bucket extension DA to mark the dependant DA as optional

cra-config.yaml, ibm_catalog.json, solutions/instance/provider.tf, solutions/instance/variables.tf, solutions/secure-cross-regional-bucket/provider.tf, solutions/secure-cross-regional-bucket/variables.tf, solutions/secure-regional-bucket/provider.tf, solutions/secure-regional-bucket/variables.tf, tests/pr_test.go
exposed [visibility](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs#visibility) value for the provider in the DA , with default value set to "private"
[Git issue](https://github.ibm.com/GoldenEye/issues/issues/11321)
exposes visibility value for the provider in the DA
```
/run pipeline
```
- Include information that users need to know about the PR in the …
=> feat:exposed visibility value for the provider in the DA

ibm_catalog.json, solutions/instance/variables.tf, solutions/secure-cross-regional-bucket/variables.tf, solutions/secure-regional-bucket/variables.tf
added CBR doc link in variable description and fixed variable name in ibm_catalog.json
adds CBR doc link in variable description and fixes variable name in ibm_catalog.json
```
/run pipeline
```
=> fix:added CBR doc link in variable description

solutions/instance/version.tf
As a best practise, provider versions should be locked in DAs to prevent potential breaking changes when new version are released
```
/run pipeline
```
=> fix: lock the time provider to specific version in the DA

main.tf
add missing `endpoint_type` to the `ibm_cos_bucket_lifecycle_configuration`
```
/run pipeline
```
=> fix: add missing `endpoint_type` to the `ibm_cos_bucket_lifecycle_configuration`

ibm_catalog.json, solutions/cross-regional-bucket/fully-configurable/variables.tf, solutions/cross-regional-bucket/security-enforced/main.tf, solutions/cross-regional-bucket/security-enforced/variables.tf, solutions/regional-bucket/fully-configurable/variables.tf, solutions/regional-bucket/security-enforced/main.tf, solutions/regional-bucket/security-enforced/variables.tf
https://github.ibm.com/GoldenEye/issues/issues/15305
Exposes `management_endpoint_type_for_bucket` in catalog.json and changes default to `direct`
```
/run pipeline
```
=> fix: exposed `management_endpoint_type_for_bucket` in catalog

variables.tf
Updated the variable validation to accept `365243` as maximum supported value for  MinimumRetention, DefaultRetention, and MaximumRetention based on this [doc](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-immutable#immutable-sdk-add-policy). This came up in content [PR](https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/931#discussion_r2267968318) review.
Updated the variable validation to accept `365243` as maximum supported value for  MinimumRetention, DefaultRetention, and MaximumRetention
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following …
=> fix: updated retention value
